-- +goose Up
-- +goose StatementBegin
CREATE TABLE notes (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id TEXT NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE notes;
-- +goose StatementEnd
